### ISSUE TITLE
Expand your example a little bit

### ISSUE THREAD

**Issue by largeDachshund** [jkuri/ng2-datepicker#1]
Juri,
Thanks for the date picker!

I'm new to Angular 2.  So, it took me a little while to figure out the syntax for your datepicker.  I'd add the following to your example:

<datepicker [(ngModel)]="test1.date" view-value="DD.MM.YYYY" model-value="DD.MM.YYYY" init-date={{test1.date}}></datepicker>

If I have an existing date, then I need to pass it into your picker. 

Thanks, again.

**Comment by jkuri** [comment]
Hi, 

No problem. I think example is pretty self explanatory, use init-date in a conjunction with model-value. 

````html
<datepicker [(ngModel)]="date" model-value="DD.MM.YYYY" init-date="12.5.2017"></datepicker>
````

But you are right. It would be better that initial date would be value passed to [(ngModel)] directive. I will fix that soon.
