### ISSUE TITLE
Syntax arrow when including datepicker

### ISSUE THREAD

**Issue by DanielDLRG** [jkuri/ng2-datepicker#10]
Hi, I obtain, the following error message once I include
`DatePicker` to the directives of my component.

> SyntaxError: expected expression, got '<'
> 	Evaluating http://localhost:3000/node_modules/ng2-datepicker/src/components/ng2-datepicker
> 	Error loading http://localhost:3000/app/main.js
> http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js
> Line 1243

To produce the error it is in fact not necessary to include the component itself into the html as e.g.
`<datepicker class="editText" [ngModel]="dateOfBirth"></datepicker>`
whereby dateOfBirth is a component property of type DATE.

I am using the version of 07. Feb. 2016.

**Comment by jkuri** [comment]
Please check the new version altought this has been problem with the `systemjs` config.
