### ISSUE TITLE
it is wrong,the days don't match the weekday

### ISSUE THREAD

**Issue by CK110** [jkuri/ng2-datepicker#111]
![image](https://cloud.githubusercontent.com/assets/9956098/21133169/8bddf914-c152-11e6-8a63-3daa36732430.png)
![image](https://cloud.githubusercontent.com/assets/9956098/21133191/a115e59e-c152-11e6-8d20-e5229e02d3c0.png)

**Comment by Sn3b** [comment]
Just noticed that too, selected my birthdate and it showed as wednesday, I was born on a thursday :D

**Comment by ashiksonic** [comment]
You could simply use this

this.options = {
            minDate: new Date(),
            firstWeekdayS```
unday: true
        };
```

**Comment by CK110** [comment]
#119
