### ISSUE TITLE
ngModel null results in today's date (should show empty)

### ISSUE THREAD

**Issue by jkumawat** [jkuri/ng2-datepicker#12]
Hi Jan,

I have been using your datepicker. I have a small question, is there any way to show empty input by default? currently, we see default today's date when model value is null. 

Any suggestion on how to get empty input by default? any configuration?

**Comment by jkumawat** [comment]
Got it working. We do not need to Initialize Date if model value is null.

**Comment by jkuri** [comment]
Glad you got it working.

**Comment by Omnisri** [comment]
hi jkumawat, 

May I know how to set the model value to null? I am looking for a solution for the same thing too.

thank you, in advance.

**Comment by rvalenciano** [comment]
@Omnisri please see this:

https://stackoverflow.com/a/48175624/3558900

**Comment by Omnisri** [comment]
@rvalenciano thankyou, so much I just stumbled upon the same solution too.. When I do this, the field is empty as expected, but when I click on the date field, the datepicker shows as "Invalid Date" to something like "Click to select a date" on the title bar. Any way to change that text? 
![image](https://user-images.githubusercontent.com/7725284/34792111-02c9b5b6-f615-11e7-97f4-a4494fb1b448.png)

Thank you, so much for responding to my question.

**Comment by rvalenciano** [comment]
@Omnisri I think we need to modify this line: https://github.com/bleenco/ng2-datepicker/blob/aff74388a8c9cc8e90b159113df7d03360b1ea44/src/ng-datepicker/ng-datepicker.component.ts#L233 to actually check if we have an empty value, then assign 'Click to select a date', I can open a PR in the next hours.

**Comment by Omnisri** [comment]
greatly appreciate prompt response @rvalenciano. I will give it a try and wait for the update :)

**Comment by Omnisri** [comment]
I have raised another issue for ng2-datepicker. anyone can take a look at it and give me some pointers please? https://github.com/bleenco/ng2-datepicker/issues/290

**Comment by rvalenciano** [comment]
@Omnisri https://github.com/bleenco/ng2-datepicker/pull/291 was merged, you can customize your message now.
