### ISSUE TITLE
emitting events

### ISSUE THREAD

**Issue by egandro** [jkuri/ng2-datepicker#121]
Hi!

What a nice component!

I wonder if it's possible to emit the events for the the component.

There is a outputEvents event, but it's not called.

Cool events would be:

-onInit()
-onOpen()
-onClose()

Thank you!

**Comment by jkuri** [comment]
hi @egandro. thanks! just commited and published to npm version with input & output events. 
for more info please see https://github.com/jkuri/ng2-datepicker/commit/9b192e730d5db1341e085dea6cfaf90bfe9c01c3.

**Comment by egandro** [comment]
Hi!

Thank you that is of great help to me!
