### ISSUE TITLE
small issue with webpack in ng2-datepicker.component.ts

### ISSUE THREAD

**Issue by egandro** [jkuri/ng2-datepicker#122]
Hi!

I noticed a small issue with ng2-datepicker.component.ts

Please prefix the following lines with "./"

  templateUrl: './ng2-datepicker.component.html',
  styleUrls: ['./ng2-datepicker.css'],

Thank you!

**Comment by jkuri** [comment]
I make everything inline so this could work for SystemJS users also.

**Comment by egandro** [comment]
thx!

**Comment by egandro** [comment]
EXCEPTION: Uncaught (in promise): Error: Error in ./DatepickerComponent class DatepickerComponent - inline template:7:6 caused by: Cannot read property 'subscribe' of undefined

Something is fishy :(

**Comment by jkuri** [comment]
I'll check on this.
