### ISSUE TITLE
how to empty the content of the input form when the ngmodel is empty  

### ISSUE THREAD

**Issue by scsenge** [jkuri/ng2-datepicker#13]
Hi @jkuri,

We are currently using this component for some applications, but we met with some problems, because we would like to empty the content of the ngmodel with a button, but the content of the input form doesn't change when the content of our ngmodel changes.

Do you have any suggestions how to empty the input?
Thanks for your work!

Csenge

**Comment by jkuri** [comment]
Hi @scsenge! I can implement a "clear" button if that makes sense?

**Comment by scsenge** [comment]
Hi @jkuri!

I would be really grateful if you could do this!

Csenge

**Comment by jkuri** [comment]
No problem, hope you are not in a hurry, but you can expect this to be done somewhere in the next week.

**Comment by jorgecasariego** [comment]
Hey @jkuri Did you implemented a "clear" button? Because I need this option too 

Thanks!!

**Comment by jkuri** [comment]
Totally forgot about that, do you guys still need that feature?

**Comment by iamdavidfrancis** [comment]
I know it's been a while, but I would love this functionality.

**Comment by vasilvalchanov** [comment]
It would be usefully to implement "clear" button, cause if I clear the input field, I clear only the "formatted" property, not the whole date object

**Comment by jkuri** [comment]
this is now resolved with "clear" button in the ui. please check `1.6.0` version. thanks.
