### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by zcsongor** [jkuri/ng2-datepicker#14]
```
d:/.../node_modules/ng2-datepicker/typings/moment/momen
t-node.d.ts(677,5): error TS2300: Duplicate identifier 'export='.
d:/.../typings/browser/definitions/moment/moment.d.ts(4
92,1): error TS2300: Duplicate identifier 'export='.
```
I have moment in my SystemJS config because of ng2-bootstrap:
'moment': `${APP_BASE}node_modules/ng2-bootstrap/node_modules/moment/moment.js`

Any idea?

Thanks!

**Comment by paulosoaresvieira** [comment]
have you solved this issue?
Currently i'm having the same problem...

**Comment by jkuri** [comment]
This should be resolved with the new version.
