### ISSUE TITLE
tslint errors

### ISSUE THREAD

**Issue by ionutVizitiu** [jkuri/ng2-datepicker#142]
Hi @jkuri ,
Thank you very much for this module.

There is a lint error in ng2-datepicker.component.ts:
ng2-datepicker/src/components/ng2-datepicker.component.ts:1:90 
    'Provider' is declared but never used.
Would you please fix it? :)

There are also a few in slimscroll.directive.ts:
ng2-slimscroll/src/directives/slimscroll.directive.ts:147:9 
    'el' is declared but never used.
ng2-slimscroll/src/directives/slimscroll.directive.ts:182:9 
    'target' is declared but never used.
ng2-slimscroll/src/directives/slimscroll.directive.ts:196:9 
    'barTop' is declared but never used.
ng2-slimscroll/src/directives/slimscroll.directive.ts:214:9 
    'body' is declared but never used.
ng2-slimscroll/src/directives/slimscroll.directive.ts:215:9 
    'el' is declared but never used.

Thank you again and I appreciate your effort!
John

**Comment by paulvmoreau** [comment]
To get around this, i had commented out the lines of offending code directly in ng2-slimscroll/src/directives/slimscroll.directive.ts
so comment out lines 147, 182, 196, 214 and 215. It'll at least get things working again until slimscroll gets fixed.

**Comment by odolha** [comment]
added [PR](https://github.com/jkuri/ng2-slimscroll/pull/43) for ng2-slimscroll, one could use the fork that fixes those issues until it's merged: `npm i --save odolha/ng2-slimscroll`
