### ISSUE TITLE
If 'ng2-datepicker' is an Angular component, then verify that it is part of this module.

### ISSUE THREAD

**Issue by jalyshen** [jkuri/ng2-datepicker#143]
I met this issue:
handleError — error_handler.js:48EXCEPTION: Uncaught (in promise): Error: Template parse errors:
'ng2-datepicker' is not a known element:
1. If 'ng2-datepicker' is an Angular component, then verify that it is part of this module.
2. If 'ng2-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<div>
  [ERROR ->]<ng2-datepicker [(ngModel)]="date"></ng2-datepicker>
  Selected date is: {{ date }}
</div>
"): ProofreadListComponent@1:2
parse@http://localhost:3000/vendor.bundle.js:26036:28 [angular]
_compileTemplate@http://localhost:3000/vendor.bundle.js:62453:56 [angular]
forEach@[native code] [angular]
_compileComponents@http://localhost:3000/vendor.bundle.js:62373:26 [angular]
createResult@http://localhost:3000/vendor.bundle.js:62269:37 [angular]
onInvoke@http://localhost:3000/vendor.bundle.js:37804:43 [angular]
run@http://localhost:3000/polyfills.bundle.js:9018:49 [angular => angular]
http://localhost:3000/polyfills.bundle.js:9425:60 [angular]
onInvokeTask@http://localhost:3000/vendor.bundle.js:37795:47 [angular]
invokeTask@http://localhost:3000/polyfills.bundle.js:9179:52 [angular]
runTask@http://localhost:3000/polyfills.bundle.js:9056:57 [<root> => angular]
drainMicroTaskQueue@http://localhost:3000/polyfills.bundle.js:9323:42 [<root>]
promiseReactionJob@[native code] [<root>]

**Comment by bjornharvold** [comment]
+1 I get same

**Comment by jalyshen** [comment]
Thanks @bjornharvold , I resolved this issue following your solution.

**Comment by bjornharvold** [comment]
Great! Thank you. Can you please create a release and push to npm? Much appreciated! There is not one good date picker out there for Angular 2 yet. You can own that space ;)

**Comment by elliotwesoff** [comment]
@bjornharvold might I ask what the solution is? I'm only seeing the problem description...

**Comment by bjornharvold** [comment]
When @jalyshen deploys a new version, it should work fine. I haven't done anything. The fix is on his side.

**Comment by Enaldi** [comment]
Did this ever get deployed? I'm having the same issue on a new install.

**Comment by FredBesterwitch** [comment]
Still Getting this Error
