### ISSUE TITLE
reset() on reactive form does not clear the component

### ISSUE THREAD

**Issue by sonicd300** [jkuri/ng2-datepicker#147]
Hi,

Im using the reactive forms in conjunction with this plugin.
Calling this.myForm.reset() should clear the previously selected date, unless there is another way to do it which is not documented.

Thanks

**Comment by jkuri** [comment]
this is now resolved with "clear" button in the ui. please check `1.6.0` version. thanks.

**Comment by sonicd300** [comment]
Can we clear this programmatically from the outside?
