### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by madhav5589** [jkuri/ng2-datepicker#15]
The demo link provided in the ReadMe is not working.

**Comment by jkuri** [comment]
Thanks, I am aware of that and will publish demo somewhere in the next week.

**Comment by fxck** [comment]
still not working?

**Comment by louisscruz** [comment]
I really wish there were a demo link!

**Comment by rolandoldengarm** [comment]
+1

**Comment by jcmartins** [comment]
+1

**Comment by HBrinkman** [comment]
+1

**Comment by yuvrajgawade** [comment]
Is this date picker working now? Because I am playing to use this in my project. Can anyone help me on this.

**Comment by Axeavius** [comment]
Any news on the demo link?

**Comment by StefanCodes** [comment]
+1

**Comment by jkuri** [comment]
Demo link finally working.
