### ISSUE TITLE
Flexibility improvements

### ISSUE THREAD

**Issue by demiro** [jkuri/ng2-datepicker#155]
Hello...

Thanks for doing the wotk...would like to implement the component..but it is really poorly done in terms of flexibility

There is one problem with icon font dependency which people mentioned before...

But there is no options to add your own classes (like appending bootstrap classes to the input elements, or having different years layout..etc)

Also saw that day names are hard coded in? Giving no opyion to use different locales

You are doing a great job in implementing the component...but imho it needs a "bit" more work on flexibility... separation of logic to themes/templates would be a great improvement

Also when implementing it with a form element... angular is complaining that the name attribute needs to be set on input element

**Comment by jkuri** [comment]
unfortunatelly I am really busy lately, but PRs are very welcome.

**Comment by demiro** [comment]
Also...the possibilty ti open the picker on input click (not only icon...disabling the editing of course)

**Comment by demiro** [comment]
Yeah.. I can imagine...thanks for your efforts anyways

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/commit/02362de1bdd609ff4709e2a3391f0eecc9078bef
