### ISSUE TITLE
Years don't reflect min/max date

### ISSUE THREAD

**Issue by demiro** [jkuri/ng2-datepicker#156]
In the code you have min year minDate-40 and maxDate+40.... why??? Why would you want to display the years that cannot be selected? 😑😑😑

**Comment by vidinev** [comment]
I can select date that earlier than minDate in following way:
1) Select year that earlier than minDate
2) Focus out from input

**Comment by zcoon** [comment]
I am having the same problem where I can select an `endDate` that is earlier than the `startDate` by changing the year of the `endDate`. This is the same issue that vidinev described. Can we have an ETA on when this issue will be fixed?

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/pull/179
