### ISSUE TITLE
Calendar button is not showing up.

### ISSUE THREAD

**Issue by udaynariseti** [jkuri/ng2-datepicker#166]
Hello,

 I am able to load the component successfully but I am not able to get the calendar button to click and select the date

Component.html -
 <ng2-datepicker [(ngModel)]="date"></ng2-datepicker>
Component.ts -

 dataForm: FormGroup;
  constructor(private formBuilder: FormBuilder) {
  }
  ngOnInit() {
    this.dataForm = this.formBuilder.group({
      date: ''
    });
  }

![image](https://cloud.githubusercontent.com/assets/6777252/22212252/f0b83392-e15d-11e6-9ca6-59c5e7601d1d.png)

Can anybody help on this?

**Comment by CliffyMk** [comment]
its using ionicons ,u need to import that also.

**Comment by udaynariseti** [comment]
Thank you. I figured it our yesterday. It is working now. Thanks for the response.

**Comment by kootenpv** [comment]
Why is this not mentioned as a requirement?

**Comment by edwinharly** [comment]
@jkuri this should be mentioned in requirements

**Comment by jkuri** [comment]
hi guys. my plan is to include inline SVG icons so this will not be needed anymore. very short on time but will try to squeze this in for the weekend.

**Comment by CliffyMk** [comment]
Just include bootstrap and font awesome icons integration :)

Manish Kumar
