### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by k4yaman** [jkuri/ng2-datepicker#17]
Hey,
i get an error on `ng install ng2-datepicker`
it outputs: 
`installing ng2`
`The 'ng generate <entity-name>' command requires an entity name to be specified. For more details, use 'ng help'.`
Also: the link in the readme isn't working:
http://jankuri.com/components/angular2-datepicker

**Comment by jkuri** [comment]
Hi! Sorry, the `ng install` command on angular-cli currently doesn't work. I need to remove that from the documentation in this repo and add it again when it will be functional.
Right now just use `ng2-datepicker.ts` file and copy it somewhere to your components. If you need any further help just let me now.
