### ISSUE TITLE
None of the images (calendar icons) are being rendered

### ISSUE THREAD

**Issue by JozefJarosciak** [jkuri/ng2-datepicker#175]
Installed Angular2 Datepicker and it all works, except I am genuinely puzzled by the fact that none of the images (calendar icons) are showing up. 

I am using Angular 2.4.4, and this is what it looks like:
![image](https://cloud.githubusercontent.com/assets/3492464/22589634/3d0ca204-e9d9-11e6-86c6-1356579df807.png)

Running "npm install mydatepicker --save" gives me the following:
![image](https://cloud.githubusercontent.com/assets/3492464/22589799/23398224-e9da-11e6-9c4b-9a2646570e9f.png)
But mydatepicker installs and as I said, functions correctly, it's just those missing images.
Does anyone care to comment as to what could be a problem here?

**Comment by tomhackettishida** [comment]
@JozefJarosciak It's using an icon font that isn't included. I had to go in and change them in `ng2-datepicker/src/ng2-datepicker/ng2-datepicker.component.html` for the library I was using. Probably not the best solution but it works for now.

**Comment by jkuri** [comment]
I believe you included some other datepicker.

**Comment by natcoxall** [comment]
I'm having the same problem, is there something specific I need to do to include the icon fonts used by ng2-datepicker?

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/commit/02362de1bdd609ff4709e2a3391f0eecc9078bef
