### ISSUE TITLE
componnet and demo not work

### ISSUE THREAD

**Issue by barbatrukko** [jkuri/ng2-datepicker#177]
Hi,
I tried to install your demo but was unable to install.

I did this (and also replaced first command by manually download from github)

- git clone https://github.com/jkuri/ng2-datepicker.git --depth 1
- npm install
- npm start

install job exit with error.
I attach the log.

Best reagrds

**Comment by barbatrukko** [comment]
[npm-debug.txt](https://github.com/jkuri/ng2-datepicker/files/754700/npm-debug.txt)

I see now that ".log" file was not attached.
renamed to .txt

Best regards

**Comment by jkuri** [comment]
fixed now.
