### ISSUE TITLE
Object to model

### ISSUE THREAD

**Issue by dotnet0509** [jkuri/ng2-datepicker#180]
I have an issue using ng2-datepicker. I appreciate any help in resolving this issue.
 
Am using the like the following:
        Start Month:<br />
        <ng2-datepicker formControlName="startMonth" [options]="calendarOptions"></ng2-datepicker> 
 
Initializing calendar options in .ts file:
 
this.calendarOptions = new DatePickerOptions({
            format: 'YYYY-MM',
            minDate: new Date(),
            maxDate: new Date()
        });
  
My “startMonth” is a string and ng2-datepicker is sending an object to the model.
 
How can I only send a string instead of object?

**Comment by jkuri** [comment]
this is desired behaviour (see readme). i would suggest you set some temporary variable and then from that var apply to the form class property.

**Comment by dotnet0509** [comment]
Thank you
