### ISSUE TITLE
Use as inline datepicker

### ISSUE THREAD

**Issue by brandenwagner** [jkuri/ng2-datepicker#19]
can this be used inline? Have the calendar always showing?

**Comment by jkuri** [comment]
Yes, set `[is-static]="true"` and it should work.

**Comment by brandenwagner** [comment]
I tried that ant its not working. i also tried [isStatic]="true"

**Comment by jkuri** [comment]
Sorry, I didn't make that feature, maybe @nirarazi can help you?

**Comment by Valeriy1991** [comment]
As far as I can see, property "isStatic" with @Input('static') decorator does not exist in ng2-datepicker.ts and index.ts today, but it exists in merge request https://github.com/jkuri/ng2-datepicker/pull/3/files... Maybe it is missed it after refactoring ng2-datepicker?

**Comment by Valeriy1991** [comment]
I think that we need to reopen this issue.

**Comment by MisterEd0105** [comment]
That would be great. Please reopen.
