### ISSUE TITLE
Not working with Bootstrap 4 and Angular 2

### ISSUE THREAD

**Issue by mappmechanic** [jkuri/ng2-datepicker#2]
Attaching the screenshot, the controls are not getting displayed.
<img width="1264" alt="screen shot 2016-01-07 at 3 31 49 pm" src="https://cloud.githubusercontent.com/assets/4088925/12167709/cd63f4a8-b553-11e5-9156-bbec7d4651f2.png">

**Comment by jkuri** [comment]
You need to include font awesome icons.
