### ISSUE TITLE
How do I configure this work with SystemJS?

### ISSUE THREAD

**Issue by avoliva** [jkuri/ng2-datepicker#202]
I don't see an index.js file or any other file for SystemJS to point to.

**Comment by jkuri** [comment]
its included on `npm` when installed from there. https://github.com/jkuri/ng2-datepicker/blob/master/package.json#L34.

**Comment by d-damien** [comment]
@avoliva Include the `.umd.js` in the `map:` attribute of your `systemjs.config.js` :

`'ng2-datepicker':    'npm:ng2-datepicker/bundles/ng2-datepicker.umd.js',`
