### ISSUE TITLE
Not working with angular-cli and angular4

### ISSUE THREAD

**Issue by dmastag** [jkuri/ng2-datepicker#209]
I tried implementing into my existing app and tried from a brand new angular-cli project. And both were giving me these problems:

![image](https://cloud.githubusercontent.com/assets/5745805/24325764/a11a59a0-11d2-11e7-8e54-bd8e73daa5be.png)

**Comment by dmastag** [comment]
Tested pull from @sandman21dan by using his ng2-datepicker-aot package and the problem went away.

**Comment by sandman21dan** [comment]
Same here, if it gets merged we can depend back on this one

**Comment by dmastag** [comment]
Now working after the #210 merge
