### ISSUE TITLE
404 error - package not found

### ISSUE THREAD

**Issue by AndroidDoctorr** [jkuri/ng2-datepicker#22]
Following the Readme example, I set up a project with the datepicker in it, but I'm getting this error when I try to run the page:

`angular2-polyfills.js:390 Error: XHR error (404 Not Found) loading http://localhost:4200/ng2-datepicker(...)`

The page just has "hello world" and the datepicker copied directly from the Readme example. Without the datepicker, it works fine, but if I include it in the HTML or if I take it out of the directives array, then I get the 404. Any idea what could be going on?

Everything is set up exactly like the Readme example

**Comment by jkuri** [comment]
Hi, please check the new readme.
