### ISSUE TITLE
How to resize width of input box

### ISSUE THREAD

**Issue by MinsuLim** [jkuri/ng2-datepicker#255]
Thank you for developing ng2-datepicker.
I tried many many other datepicker libraries with ng2. 
But this is the only one that satisfy my needs. 

well.. I have a question about how to resize width of input box.
Default size is 160px but I want to resize to 100px.
Help me please and Thx in advance.

![image](https://user-images.githubusercontent.com/16252347/30367305-e12da698-98a8-11e7-8fea-a7bbf2611296.png)

**Comment by jkuri** [comment]
hi @MinsuLim. you need to override that property https://github.com/jkuri/ng2-datepicker/blob/master/src/ng2-datepicker/ng2-datepicker.component.sass#L25.

**Comment by MinsuLim** [comment]
hi @jkuri . Thank you for quick response. 
I resolved that figure by adding code below in my component. 
    styles:[`
            /deep/ .datepicker-container .datepicker-input-container .datepicker-input{
                width: 100px !important;
            }
    `]

/deep/ and !important was necessary though.
Thank you very much.

**Comment by ShiruJan** [comment]
i have the same problem, and use the CSS not work.
