### ISSUE TITLE
Unit test is failling

### ISSUE THREAD

**Issue by bun-enoikio** [jkuri/ng2-datepicker#257]
Hi jkuri,
I am not sure if this issue is already reported or not but I am trying to integrate with my angular 2 it keeps complaining about:
Error at /node_modules/ng2-datepicker/src/ng-datepicker/ng-datepicker.component.ts:2:29: 'ControlValueAccessor' is declared but never used.
Error at /node_modules/ng2-datepicker/src/ng-datepicker/ng-datepicker.component.ts:6:3: 'addDays' is declared but never used.
Error at /node_modules/ng2-datepicker/src/ng-datepicker/ng-datepicker.component.ts:217:55: 'onBlur' is declared but never used.
I think some variables got declare but never used.

Can you look into this issue?
Thanks,
-Bun

**Comment by jkuri** [comment]
hi. thanks for the report, I will check on it later

**Comment by jkuri** [comment]
please check now

**Comment by bun-enoikio** [comment]
Thanks jkuri for a really quick fix, but I am not able to pull the 2.0.3 version. looks like 2.0.3 is not available yet.
-Bun

**Comment by jkuri** [comment]
sorry, I forgot to publish

**Comment by bun-enoikio** [comment]
Thanks jkuri. It's all good.
-Bun
