### ISSUE TITLE
no exported members

### ISSUE THREAD

**Issue by ja5onkendall** [jkuri/ng2-datepicker#259]
Updated to latest version from 1.8.3 to 2.1.0 and my builds are failing with 'DatePickerOptions and DateModel has no exported members'. Were there breaking changes in the latest build?

**Comment by jkuri** [comment]
hi. it has been rewriten from schratch. downgrade back to 1.x.x or check the readme please.

**Comment by VVildVVolf** [comment]
Hi, Does the updated version support locale? unfortunately I do not see this options:( or maybe I can add it again, if it does not?

**Comment by jkuri** [comment]
hi @VVildVVolf. the new version is based on `date-fns` rather than `moment`. I did not put extra effort in the localization, would be nice if you can do it if you have time?

**Comment by VVildVVolf** [comment]
I will try to do it as fast as I can, if you will review it and include to the release:) because I need for this functionality, but I did not see that even in the previous releases, I thought it would be included with the next releases but now it is cut down:(

**Comment by ja5onkendall** [comment]
@jkuri Ok cool, thank you.
