### ISSUE TITLE
Cannot Pick First Date of The Month (IMPORTANT)

### ISSUE THREAD

**Issue by agungsb** [jkuri/ng2-datepicker#27]
Hi, I just found a bug where the user can't pick the 1st date of the month if the 2nd date is on Monday of the first week. The examples are on February 2015 and March 2015. User can't pick 1st February nor 1st March because the date doesn't appear anywhere (whether in the previous month nor the current month). How to solve this? Thank you.

**Comment by Davy-F** [comment]
It's working ok for me?
![image](https://cloud.githubusercontent.com/assets/19592376/15775612/b851469c-297a-11e6-9220-0553e5e77b62.png)

**Comment by agungsb** [comment]
Well, it's strange. I even have updated but the problem persisted. But I finally managed to solve the problem by did some customization on the plugin.
