### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by softgandhi** [jkuri/ng2-datepicker#28]
Demo link not working.
It simply says :-)

**Comment by mickeyshi** [comment]
Yeah, seems like an extra 'r' was typo'ed in. The link should be 

[http://demo.jankuri.com/ng2-datepicker/](url)

**Comment by jkuri** [comment]
it is now :)

**Comment by softgandhi** [comment]
It works now. Thank you.

**Comment by uzumakinaruto123** [comment]
not working now

**Comment by jkuri** [comment]
it does again :-)
