### ISSUE TITLE
fails on install typings

### ISSUE THREAD

**Issue by chambersDon** [jkuri/ng2-datepicker#35]
I have tried to install this but it fails on: postinstall: `typings install`.

I updated packages.json and the output is below.  I've also tried a manual npm install with similar results.

PATH=C:\Program Files\nodejs;.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files\nodejs\npm.CMD" install ng2-datepicker
> ng2-datepicker@0.7.3 postinstall C:\Projects\Rebus\FMS\Code\Current\FMSSupport\src\Angular2Client\node_modules\ng2-datepicker
> typings install
'typings' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/forms@0.1.1 requires a peer of @angular/common@2.0.0-rc.3 but none was installed.
npm WARN @angular/forms@0.1.1 requires a peer of @angular/compiler@2.0.0-rc.3 but none was installed.
npm WARN @angular/forms@0.1.1 requires a peer of @angular/core@2.0.0-rc.3 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/http@2.0.0-rc.2 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ng2-datepicker"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ng2-datepicker@0.7.3 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-datepicker@0.7.3 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-datepicker package,
npm ERR! not with npm itself.
**npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install**
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-datepicker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-datepicker
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Rebus\FMS\Code\Current\FMSSupport\src\Angular2Client\npm-debug.log

**Comment by morocarlo** [comment]
hi, install typings with:
"npm install -g typings"

**Comment by chambersDon** [comment]
That didn't help.

It says it installed typing 1.3.2.  Then I add "ng2-datepicker": "0.7.3" to package.json and it will not isntall.  It still fails on:
 ng2-datepicker@0.7.3 postinstall: `typings install`
npm ERR! Exit status 1

**Comment by jkuri** [comment]
I'll update to @types today.

**Comment by jkuri** [comment]
This should now be resolved.
