### ISSUE TITLE
ng2-datepicker not working in IE11

### ISSUE THREAD

**Issue by NitinTiwari1010** [jkuri/ng2-datepicker#38]
Demo is working fine on IE 11 but after implementation it is not showing calendar on IE 11, working fine on crome.

**Comment by jkuri** [comment]
Hi, I still need to refactor the whole component which I will do somewhere in the next week.

**Comment by NitinTiwari1010** [comment]
Thanks for the quick response, component is working good, I am using it with angular-cli, Is there any work around for IE 11 fix?

**Comment by jkuri** [comment]
Can you paste me the output of console? Currently I don't have any access to IE so I cannot check it.

**Comment by NitinTiwari1010** [comment]
I got the issue, it was because of page css which is creating a problem. Thanks a lot for your support. working good on IE 11 as well.

**Comment by knottydon** [comment]
Encountering error in IE11:

![image](https://user-images.githubusercontent.com/2860498/30527108-7d964d08-9c57-11e7-80c9-53dc66e7d3e0.png)

How can i fix this problem? any help? thank you
