### ISSUE TITLE
Still not working in RC5 because of wrong dependencies

### ISSUE THREAD

**Issue by juwil** [jkuri/ng2-datepicker#43]
for some reason ng2-datepicker uses forms-deprecated. It is not clear form it's dependencies (which are bad defined by not using a version but github:angular/common-builds etc)
So when one is bootstrapping the app by
`platformBrowserDynamic().bootstrapModule(AppModule);`
the app won't start because of the exception below. After removing the Datepicker directive in my component, the application loads again (but without the datepicker..)

```
// ---------------------------------------------------------------------------------------
import {Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import {TranslatePipe} from 'ng2-translate/ng2-translate';
import { 
  FormBuilder,
  FormGroup,
  FormControl,
  Validators
} from '@angular/forms';
import {DatePicker} from "ng2-datepicker";
import {FirmwareService} from "../../service/firmware.service";
import {FirmwareUploadModel} from "../../model/firmware.model";
import {ValidationService} from "../../service/validation.service";
import {ControlMessagesComponent} from "../../control-messages/control-messages.component";

@Component({
  moduleId: module.id,
  selector: 'app-firmware-modal',
  templateUrl: 'modal.component.html',
  directives: [DatePicker, ControlMessagesComponent],
  providers: [FirmwareService],
  pipes: [TranslatePipe]
})
export class MyComp ..

// ---------------------------------------------------------------------------------------
```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/app/my-comp/my-comp.component.html:65:20
ORIGINAL EXCEPTION: No value accessor for form control with unspecified name
ORIGINAL STACKTRACE:
BaseException@http://localhost:4200/vendor/@angular/common/src/facade/exceptions.js:27:23
_throwError@http://localhost:4200/vendor/@angular/common/src/forms-deprecated/directives/shared.js:64:11

**Comment by jkuri** [comment]
Hey @juwil, this looks like a problem with your configuration, not the module. If you need any help configuring this or a sample config let me know.

**Comment by curlyfro** [comment]
i'm getting the same error.  i'm using rc5.  can you include a demo.html page?

**Comment by jkuri** [comment]
This should be resolved; https://github.com/jkuri/ng2-datepicker/commit/41426ab95add6b84e9fc93d102c6d729b4586c90
