### ISSUE TITLE
Not able to use it in rc5 FormGroup

### ISSUE THREAD

**Issue by 4rpit** [jkuri/ng2-datepicker#47]
Hi, 
While using datepicker with rc5 formgroup I am getting this,
**No value accessor for form control with name: 'startDate'** 
I have given a formControlName to datepicker in this case.
` <datepicker [(ngModel)]="data.startDate" model-format="YYYY-MM-DD" formControlName = "startDate"></datepicker>`
 and also not able to use it with **ngDefaultControl**  in datepicker.
` <datepicker [(ngModel)]="data.startDate" model-format="YYYY-MM-DD" ngDefaultControl></datepicker>`
Any Help!

**Comment by jkuri** [comment]
Hi, `ng2-datepicker` is deprecated. Please check https://github.com/jkuri/ng2-ui-kit.
