### ISSUE TITLE
Install with Angular CLI

### ISSUE THREAD

**Issue by igisav** [jkuri/ng2-datepicker#49]
Is there a way to install datepicker into existing project created by angular-cli ?

Using `npm install` just copy repository to node_modules and doesn't creates js-file, required by "[installation of 3rd party libs](https://github.com/angular/angular-cli/wiki/3rd-party-libs)"

**Comment by jkuri** [comment]
Hi @igisav, if you use newer versions of `angular-cli` (which is recommended) you just import 
`import {DatePicker} from 'ng2-datepicker';` in `app.module.ts` and it will be bundled within your app.

**Comment by igisav** [comment]
That is a problem - we use old version 1.0.0-beta.10. The update of new with webpack is a nightmare.

**Comment by jkuri** [comment]
You can still configure SystemJS configuration mappings to `ng2-datepicker.js`, the module comes with compiled files. Then instead of importing `{DatePicker}` into `NgModule` add it to `directives: [...]` in component you are using it.

**Comment by igisav** [comment]
The module comes NOT with compiled files. if I do `npm install` or `ng install` I have only .ts files in `node_modules`

**Comment by jkuri** [comment]
@igisav you were right. try again please.

**Comment by igisav** [comment]
No. Still don't work. I got:
` Typescript found the following errors:/app/app.component.ts (4, 28): Cannot find module 'ng2-datepicker'`

**angular-cli-build.js**:
```
vendorNpmFiles: [
      ...
      'ng2-datepicker/**/*.+(js|js.map)'
    ]
```

**system-config.js**:
```
const map: any = { "ng2-datepicker":   "vendor/ng2-datepicker"};
const packages: any = {
   'ng2-datepicker':    { main: 'ng2-datepicker.js', format: 'cjs'}
};
```

**app.component.ts**:
```
import { DatePicker } from "ng2-datepicker";
...
directives: [DatePicker],
....
```

**Comment by jkuri** [comment]
`ng2-datepicker/**/*.+(js|js.map)`, not sure if that `+` sign is correct, try wildcard instead. Also, debug your app in developer console network tab, it it's not loaded - its problem with your configuration, not the module itself.

**Comment by igisav** [comment]
I give up :(

It throw one error after another. I assume, it depends with `"typings": "ng2-datepicker.d.ts",`in package.json in [your commit](https://github.com/jkuri/ng2-datepicker/commit/9cbfff369ad49e5f1be4ff340836c54e9f208175) .... 

I'll try to upgrade whole project to new angular-cli...

Thank you, anyway.

**Comment by jkuri** [comment]
sorry, It's been a while when I was last using configuration with SystemJS and cannot tell you the configuration from the head. Maybe if you can attach a zip I can take a look.

**Comment by jkuri** [comment]
but yes, upgrading your app won't do any harm as RC6 is definitely more like the final release then the one you have now.

**Comment by armno** [comment]
maybe a bit too late but here is how I put this module with angular-cli

- angular-cli 1.0.0-beta.14
- angular 2.0.0
- ng2-datepicker 1.0.6

```sh
$ npm install ng2-datepicker
```

in `app.module.ts`

```ts
// import datepicker component
import { DatePicker } from 'ng2-datepicker/ng2-datepicker';

// the put the component in `declarations` option
@NgModule({
  declarations: [
    AppComponent,
    DatePicker,
    ...
  ]
})
```

that's it. `<datepicker>` is available to the app. hope it helps.

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/pull/62

**Comment by sunillokhande** [comment]
can anybody has solution for this : 
I am using md2-datepicker with angular cli. I am getting the below error while "ng serve" but app works fine with the date picker but "ng build --prod" is not working.

Error : 
ERROR in Error encountered resolving symbol values statically. Calling function 'Md2DatepickerModule', function calls are not supported. Consider replacing the function or lambda with a
reference to an exported function, resolving symbol AppModule in D:/HubnetAmazon/Trunk/HubnetAngular2UI/hubnet-new-ui/src/app/app.module.ts, resolving symbol AppModule in D:/HubnetAmazon
/Trunk/HubnetAngular2UI/hubnet-new-ui/src/app/app.module.ts

My OS : windows 7 64 bit
My Angular Cli version : 1.0.0-rc.0
My Md2DatepickerModule Version : 0.0.1-alpha.1
