### ISSUE TITLE
angular 2 2.0.0

### ISSUE THREAD

**Issue by grauschnabel** [jkuri/ng2-datepicker#51]
hi there,

will there be a version for angular 2.0.0 ?

**Comment by jkuri** [comment]
Hey,

This is a version for 2.0.0.

**Comment by NightImmunity** [comment]
I'm working on a version for the official release:  https://github.com/NightImmunity/ng2-datepicker.  I'm going to try to use it in another app to see if it works.

**Comment by jkuri** [comment]
@NightImmunity for what official release :) if you have any bug fixes feel free to submit a PR. otherwise feel free to do with this what you want, its MIT licenced :)

**Comment by NightImmunity** [comment]
@jkuri For the official release of Angular2! ;) Also, thanks for the heads up.  Right now I'm just trying to get this exported as a module so it can be integrated with NgModules.

**Comment by fahad-nxvt** [comment]
Any ETA on this?

**Comment by connecttheworld** [comment]
I think I'm going to write one from "scratch" starting tonight.

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/pull/62
