### ISSUE TITLE
Datepicker stacking on top of calendar

### ISSUE THREAD

**Issue by NightImmunity** [jkuri/ng2-datepicker#53]
Maybe this was a bug I introduced after making changes to my forked copy.  But whenever I have one datepicker on top of another one, and select the datepicker on top, the datepicker on the bottom appears on top of the calendar that popped up from the above datepicker.

![ng2-datepicker-5](https://cloud.githubusercontent.com/assets/22245689/18683984/32ae8a54-7f38-11e6-8370-46f795a4c153.png)

Have you seen this before?  At first I thought that I could fix it by setting the z-index of the calendar and datepicker, but I don't think that fixes it.

**Comment by jkuri** [comment]
increasing `z-index` for calendar container should solve this.

**Comment by NightImmunity** [comment]
I tried setting z-index on various elements in the browser's dev tools.  I need to look into how z-index works.

**Comment by jkuri** [comment]
try setting `z-index` on `.ui-kit-calendar-container .ui-kit-calendar-cal-container` and set it to more than 99.

**Comment by NightImmunity** [comment]
That didn't work by itself for me.  I also had to set a z-index of <99 on the datepicker element itself.  I don't know why I didn't think of that sooner :)
