### ISSUE TITLE
Move@types/moment to dev dependencies

### ISSUE THREAD

**Issue by piizei** [jkuri/ng2-datepicker#59]
Would it be possible to change the dependency of types/moment to development dependency? It is causing problems when inherited to JSPM/Typings project.

**Comment by jkuri** [comment]
Yes, if you can prepare PR for this I'll accept it right away. Thanks

**Comment by piizei** [comment]
Ok, will do. Thanks :)

**Comment by piizei** [comment]
Tested and working, thanks.
