### ISSUE TITLE
Please add a default export to support angular-cli auto install feature

### ISSUE THREAD

**Issue by agungsb** [jkuri/ng2-datepicker#6]
> It would be great if this library provided a default export object as described here in the angular-cli Publisher's Guide. Our project would greatly benefit from it and it's very easy to do. Please comment back if that would be possible. If you won't have time in the next couple days, I will try to submit a PR to provide this compatibility soon. Thank you!

**Comment by jkuri** [comment]
I am planning to do this in the next days.

**Comment by agungsb** [comment]
Okay. Thank you very much. I'm so excited to use this plugin with anguar-cli.

**Comment by jkuri** [comment]
Done. Please see the readme.

**Comment by agungsb** [comment]
Hi, @jkuri . I've tried to follow the instruction but everytime I run the `ng install ng2-datepicker` command, I always get the following error:

> The `ember generate <entity-name>` command requires an entity name to be specifi
> ed. For more details, use `ember help`.

**Comment by jkuri** [comment]
Please try following the whole install procedure and make sure you linked `angular-cli` correctly. Also make sure you are not using `ng new` inside `angular-cli/` directory which you cloned before. 
If any problems persist feel free to write here again.

**Comment by agungsb** [comment]
Hi @jkuri . I've followed the procedure correctly, but now I got the following error everytime I run `ng install ng2-datepicker` command:

> Cannot find module 'npm'
> Error: Cannot find module 'npm'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:289:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Class.module.exports.Task.extend.init (F:\ANGULARJS\angular-cli\addon\ng2
> \tasks\lib-install.js:22:28)
>     at new Class (F:\ANGULARJS\angular-cli\node_modules\angular-cli\node_modules
> \core-object\core-object.js:18:12)
>     at Class.module.exports.Command.extend.run (F:\ANGULARJS\angular-cli\addon\n
> g2\commands\install.js:24:26)
>     at Class.<anonymous> (F:\ANGULARJS\angular-cli\node_modules\angular-cli\lib\
> models\command.js:151:17)
>     at lib$rsvp$$internal$$tryCatch (F:\ANGULARJS\angular-cli\node_modules\angul
> ar-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
>     at lib$rsvp$$internal$$invokeCallback (F:\ANGULARJS\angular-cli\node_modules
> \angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)

**Comment by jkuri** [comment]
Try `npm link npm` and then try again.

**Comment by agungsb** [comment]
I think I have successfully installed the plugin. But when I run the browser, I got following error in the console.log: 

> GET http://localhost:4200/ng2-datepicker 404 (Not Found)

It seems that there is a problem with linking the source file. How do I solve this?

**Comment by jkuri** [comment]
Please check the source of generated html, then check the source of thirdparty/libs.js ... is it empty?

**Comment by agungsb** [comment]
Do you mean the file inside the dist folder?

All I got inside the index.html's body tag is as follow:

```
<script src="vendor/systemjs/dist/system.src.js"></script>
    <script src="vendor/rxjs/bundles/Rx.js"></script>
    <script src="vendor/angular2/bundles/angular2.dev.js"></script>
    <script src="vendor/angular2/bundles/http.dev.js"></script>
    <script src="vendor/angular2/bundles/router.dev.js"></script>
```

As you see, there's no such thing as thirdparty/libs.js

:(

**Comment by jkuri** [comment]
That means you didn't follow the instructions but you installed angular-cli via npm, or you forgot to `npm link angular-cli`in your project. Please follow the instructions, I really can't help you more than providing exact commands, what can go wrong?

**Comment by jkuri** [comment]
`git clone https://github.com/angular/angular-cli.git && cd angular-cli && npm install && npm link && cd .. && ng new your-project-name && cd your-project-name && npm link angular-cli && ng install ng2-datepicker && ng serve` 
copy & paste that into terminal, then open your browser at `localhost:4200`.

**Comment by agungsb** [comment]
Thanks @jkuri . It works really well. Now I wonder how to implement it to an existing project. I think it's difficult for me to generate all new project just to implement this plugin and build everything all over again.

Anyway, thank you very much. Nice plugin! Have a nice day! :+1:

**Comment by jkuri** [comment]
Np.
