### ISSUE TITLE
Works locally, not when built

### ISSUE THREAD

**Issue by tomhackettishida** [jkuri/ng2-datepicker#61]
The datepicker works fine when run locally, but when I build the project (using CLI) and upload it to a server it refuses to work at all.

`EXCEPTION: No value accessor for form control with unspecified name attribute`

Any ideas? Thanks.

EDIT: It works when I do ng build, but not when I do ng build --prod

**Comment by jkuri** [comment]
Honestly I don't have an idea currently, did you maybe solved this at this point?

**Comment by tomhackettishida** [comment]
Updating both Angular and ng2-datepicker solver the issue
