### ISSUE TITLE
Latest version broke webpack using with angular-cli

### ISSUE THREAD

**Issue by elvirdolic** [jkuri/ng2-datepicker#68]
Hi,

using latest version brokes the intergration with angular-cli

rror: Uncaught (in promise): Error: moduleId should be a string in "DatePickerComponent".

br

**Comment by m4mbart** [comment]
Yes it seems to brake the entire build for webpack... SystemJS is probably fine.

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/commit/c845e07106234bc539af4d7045786b856f67b00a
