### ISSUE TITLE
Can't run it with angular 2.0.2

### ISSUE THREAD

**Issue by OneOfOne** [jkuri/ng2-datepicker#69]
I had to install `@types/node` to make it stop complaining about missing `module.id`, however trying to run the actual app I ended up with:

```
compiler.umd.min.js:21 
Uncaught Error: moduleId should be a string in "DatePickerComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```

Any ideas?

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/commit/c845e07106234bc539af4d7045786b856f67b00a
