### ISSUE TITLE
Controls don't appear

### ISSUE THREAD

**Issue by agungsb** [jkuri/ng2-datepicker#7]
I've successfully installed the plugin with angular-cli. But the problem is, the controls of the plugin (previous and next buttons for changing month and year) don't appear. This is strange because if I see the demo, the controls should be there. I also inspected the elements using the chrome tools, and I see the elements there. But the elements simply do no nothing. Can you please check? Thanks again.

**Comment by jkuri** [comment]
Please include fontawesome library into your index.html.
