### ISSUE TITLE
Make datepicker customizable

### ISSUE THREAD

**Issue by ghetolay** [jkuri/ng2-datepicker#72]
Hi,

Datepicker is complicated ui element because everybody wants to render it differently. You just have to look at all the implementations available. For me none fits, I would need a mix of different approach. We could just take your issue #52 about year control, some does not need it, some wants double arrow and I'm more for a dropdown menu.

With angular 2 and ng-content I think we should be able to create a component flexible enough to cover all needs. I'm thinking about a `DatePickerCore` with a good API to be manipulated, a minimal static template and using multiple `<ng-content>` for the rest of the template. Then we could create some of the most common datepicker on top of that core (`DatePickerMinimal`, `DatePickerFull`) and for *uncommon* users like me, they could still create their own component based on `DatePickerCore`.

I could start working on yet another datepicker plugin but, if you are up to it, I would rather rally with you so we could build a good and flexible datepicker plugin for once.

**Comment by jkuri** [comment]
@ghetolay that sounds like a perfect idea, really. unfortunately I am really busy lately, but if you are prepared to contribute on this one I can add you to the repo and you develop this on a separate branch. that would be awesome.

**Comment by ghetolay** [comment]
@jkuri Yep no problem let's do it.

How should we proceed to discuss about specs ? Is opening issues ok ?

**Comment by jkuri** [comment]
yes, that should be fine I think

**Comment by ghetolay** [comment]
Closed in favor of #76.
