### ISSUE TITLE
Changing the style of the input

### ISSUE THREAD

**Issue by eliezerreis** [jkuri/ng2-datepicker#9]
Hi,

Should be nice to allow developers change the style of the input. I'm using this component but he is really different from the rest of the page.

Best regards,

**Comment by jkuri** [comment]
Hi,

just set the style to `.ng-datepicker-input` class and it shoud work.

**Comment by antontruong** [comment]
Hello,

your datepicker is awesome and I would really like to customize the appearance of the input fields, but from the above conversation I cannot figure out how to do it.

Thx.


Anton

**Comment by jkuri** [comment]
hi @antontruong, check `.css` file that comes with module, then apply your styles on same classes like in that file but after this component, in some separate css or inside your current styles. that styles will then be overriden and visible in browser.

**Comment by antontruong** [comment]
Hi jkuri,

first thx for your fast reply. I could solve my problems with your hints. I have seen that you are working on the 2nd version of your datepicker and that you adds a locale feature.
Can I somehow contribute for a german(maybe chinese too) translation? And could you tell where to start (i mean I have seen that there is a 2.0.0-dev tag but could find any translation files) ?


Best regards,

Anton

Von: Jan Kuri [mailto:notifications@github.com]
Gesendet: Montag, 6. März 2017 18:16
An: jkuri/ng2-datepicker <ng2-datepicker@noreply.github.com>
Cc: Anton Truong <anton.truong@itas-gmbh.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jkuri/ng2-datepicker] Changing the style of the input (#9)


hi @antontruong<https://github.com/antontruong>, check .css file that comes with module, then apply your styles on same classes like in that file but after this component, in some separate css or inside your current styles. that styles will then be overriden and visible in browser.

**Comment by bernardold** [comment]
Hi.
You might've already solved your problem. Writing for future reference though.

In my particular case I had to personalize the entire component (including the calendar itself). It is a little bit of a hassle to get privilege over the component's default style by overriding it without using _!important_ declaration.
My hint is: Try surrounding the directive with a custom div and be as specific as you can to select the classes.

To the developers: Please use the advantage of using SASS with the project and declare the overridable style with _!default_. Abusing on variables would help as well.

Best Regards

Bernardo Duarte
