### ISSUE TITLE
Unable to initialize the date picker with current date

### ISSUE THREAD

**Issue by nelaturuk** [jkuri/ng2-datepicker#90]
Any sample you could give for loading up the datepicker with initial date value?

**Comment by orlandobrea** [comment]
I have the same problem. I've changed the method writeValue(value: any) in ng2-datepicker.ts to this

```
  writeValue(value: any) {
    let receivedDate = moment(value);
    this.viewDate = receivedDate.format(this.viewFormat);
  }
```
I did a quick test and it's working

**Comment by nelaturuk** [comment]
Initializing the model value to moment() worked for me.
