### ISSUE TITLE
[ts] Cannot find module 'ng2-datepicker/ng2-datepicker'.

### ISSUE THREAD

**Issue by shay972** [jkuri/ng2-datepicker#96]
C:\Users\shayb\Desktop\AutomationWeb\plunk>npm install ng2-datepicker --save
angular-quickstart@1.0.0 C:\Users\shayb\Desktop\AutomationWeb\plunk
`-- ng2-datepicker@2.0.0-dev5

when trying to import:
import { DatePicker } from 'ng2-datepicker/ng2-datepicker';

getting:
[ts] Cannot find module 'ng2-datepicker/ng2-datepicker'.

**Comment by ghetolay** [comment]
I don't know why it's installing v2.0.0-dev5 by default.
You may want to install ng2-datepicker@1.1.1 in the meantime.

**Comment by shay972** [comment]
Thanks, solved
