### ISSUE TITLE
ngModule not working

### ISSUE THREAD

**Issue by dabicho** [jkuri/ng2-datepicker#98]
binding return value with ngModule is not working for me (Followed example from npm page). 
Am I missing something?
I forked the demo plunkr from https://www.npmjs.com/package/ng2-datepicker as an example
https://plnkr.co/edit/Bpfghssx2awAKMGFiV9d?p=preview

**Comment by ghetolay** [comment]
Your plunker seems to work fine.
Do you want `myModel` to contain the date ?

**Comment by dabicho** [comment]
Oh, the input is alright. That was just a test. 
It is the return value from the calendar who is not binding to date from the component. 
After selecting a date, the date should be printed.
I can work around it with the (onDateChange) event though.

**Comment by ghetolay** [comment]
This is because of the two-way binding. 
You should do `[(ngModel)]` not `([ngModel])`.

**Comment by dabicho** [comment]
I have just noticed that.
Sorry, I copied the code from the npm page and didn't notice.
Thank you.
